apiVersion: v1
kind: PersistentVolume
metadata:
  name: book-postgresql-data-pv
  namespace: book-store
  labels:
    app: book-postgresql-data-pv
    app-type: storage
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/minhcv/data/book"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: book-postgresql-data-pvc
  namespace: book-store
  labels:
    app: book-postgresql-data-pvc
    app-type: storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
