apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: book-postgresql-data-pvc
  namespace: book-store
  labels:
    app: book-postgresql-data-pvc
    app-type: storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
