apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-deployment
  namespace: book-store
  labels:
    app: book-service-deployment
spec:
  replicas: 2
  template:
    metadata:
      name: book-service-deployment
      labels:
        app: book-service-deployment
        app-type: service-endpoint
    spec:
      containers:
        - name: book-service-deployment
          image: book-service:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: book-service-deployment
