apiVersion: v1
kind: Service
metadata:
  name: book-postgres-service-np
  namespace: book-store
spec:
  selector:
    app: book-postgres-deployment
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30013
  type: NodePort
