apiVersion: v1
kind: Service
metadata:
  name: book-postgres-service-lb
  namespace: book-store
spec:
  selector:
    app: book-postgres-deployment
  ports:
    - port: 5432
      targetPort: 5432
  type: LoadBalancer
