apiVersion: v1
kind: Service
metadata:
  name: book-service-service
  namespace: book-store
spec:
  selector:
    app: book-service-deployment
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30003
  type: NodePort
