apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service-lb
  namespace: book-store
spec:
  selector:
    app: eureka-server-deployment
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30009
  type: LoadBalancer
