apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data-pv
  namespace: book-store
  labels:
    app: postgresql-data-pv
    app-type: storage
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/minhcv/data"
