apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: book-store
  labels:
    app: postgres
    app-type: secret
data:
  # echo -n "postgres" | base64
  POSTGRES_DB: cG9zdGdyZXM=
  # echo -n "book" | base64
  BOOK_POSTGRES_USER: Ym9vaw==
  # echo -n "postgres" | base64
  BOOK_POSTGRES_PASSWORD: cG9zdGdyZXM=
  # echo -n "user" | base64
  kubeUSER_POSTGRES_USER: dXNlcg==
  # echo -n "postgres" | base64
  USER_POSTGRES_PASSWORD: cG9zdGdyZXM=
  # echo -n "order" | base64
  ORDER_POSTGRES_USER: b3JkZXI=
  # echo -n "postgres" | base64
  ORDER_POSTGRES_PASSWORD: cG9zdGdyZXM=
