apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: book-store
  labels:
    app: postgres
    app-type: secret
data:
  # echo -n "postgres" | base64
  BOOK_POSTGRES_DB: cG9zdGdyZXM=
  # echo -n "book" | base64
  BOOK_POSTGRES_USER: Ym9vaw==
  # echo -n "postgres" | base64
  BOOK_POSTGRES_PASSWORD: cG9zdGdyZXM=
