apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: book-store
  labels:
    app: postgres
    app-type: secret
data:
  # echo "books" | base64
  BOOK_POSTGRES_DB: Ym9va3MK
  # echo "book" | base64
  BOOK_POSTGRES_USER: Ym9vawo=
  # echo "postgres" | base64
  BOOK_POSTGRES_PASSWORD: cG9zdGdyZXMK
